[package]
name = "metaboss_lib"
version = "0.0.9"
edition = "2021"
description = "The core library for the metaboss cli."
repository = "https://github.com/samuelvanderwaal/metaboss_lib"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
retry = "1.3.0"
mpl-token-metadata = "1.4"
serde = { version = "1.0", features = ["derive"] }
solana-account-decoder = "1.10"
solana-client = "1.10"
solana-program = "1.10"
solana-sdk = "1.10"
spl-associated-token-account = "~1.0.5"
spl-token = "3.2.0"
thiserror = "1.0.30"
